# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: POC da Intranet
email: nicolas.ibanheiz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Projeto utilizado como prova de conceito para o modelo da nova Intranet da DP6.
twitter_username: jekyllrb
github_username:  Ibanheiz

# Build settings
markdown: kramdown
permalink:  /:title

prose:
  rooturl: '_posts'
  siteurl: 'https://dp6.github.io/starter/'
  relativeLinks: 'https://dp6.github.io/starter/links.jsonp'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""