title: DP6 - Centro de inovações
initiative: ""
description: >- # this means to ignore newlines until "baseurl:"
  DP6 - Bringing Science to Digital Marketing DP6

url: "https://dp6.github.io" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed
    jekyll-github-metadata

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

