title: DP6 - Centro de inovações
initiative: ""
description: >- # this means to ignore newlines until "baseurl:"
  DP6 - Bringing Science to Digital Marketing DP6

url: "https://dp6.github.io" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-gzip

defaults:
  -
    scope:
      path:            "case-dp6"
    values:
      sitemap:         false

# Build settings
repository: dp6/dp6.github.io

