name: Update all github pages

on:
  schedule:
    - cron: "30 0 * * *"

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install jq
      run: apt-get update && apt-get install --no-install-recommends -y jq findutils curl ca-certificates

    - name: Update respositories public with gh-page
      run: sh build-github-pages-dp6.sh ${{ secrets.GH_PAGES_USER }} ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}